export const productsList:Record<string,unknown>[] = [
  {
    "id": 1,
    "name": "Wireless Bluetooth Headphones",
    "description": "Noise cancelling over-ear headphones with 30 hours battery life.",
    "price": 2999,
    "currency": "INR",
    "category": "Electronics",
    "stock": 45,
    "rating": 4.5,
    "image": "https://example.com/images/headphones.jpg",
    "brand": "SoundMax",
    "createdAt": "2026-02-01T10:00:00Z"
  },
  {
    "id": 2,
    "name": "Smart Fitness Watch",
    "description": "Track heart rate, sleep and daily activities.",
    "price": 4999,
    "currency": "INR",
    "category": "Wearables",
    "stock": 30,
    "rating": 4.2,
    "image": "https://example.com/images/watch.jpg",
    "brand": "FitPro",
    "createdAt": "2026-02-02T11:00:00Z"
  },
  {
    "id": 3,
    "name": "Gaming Mechanical Keyboard",
    "description": "RGB backlit mechanical keyboard with blue switches.",
    "price": 2499,
    "currency": "INR",
    "category": "Electronics",
    "stock": 60,
    "rating": 4.7,
    "image": "https://example.com/images/keyboard.jpg",
    "brand": "KeyStorm",
    "createdAt": "2026-02-03T09:30:00Z"
  },
  {
    "id": 4,
    "name": "Running Shoes",
    "description": "Lightweight breathable sports running shoes.",
    "price": 1999,
    "currency": "INR",
    "category": "Footwear",
    "stock": 80,
    "rating": 4.1,
    "image": "https://example.com/images/shoes.jpg",
    "brand": "RunFast",
    "createdAt": "2026-02-04T08:15:00Z"
  },
  {
    "id": 5,
    "name": "Laptop Backpack",
    "description": "Water-resistant backpack fits up to 15.6 inch laptop.",
    "price": 1499,
    "currency": "INR",
    "category": "Accessories",
    "stock": 100,
    "rating": 4.3,
    "image": "https://example.com/images/backpack.jpg",
    "brand": "CarryPro",
    "createdAt": "2026-02-05T12:45:00Z"
  },
  {
    "id": 6,
    "name": "Smartphone 128GB",
    "description": "6.5-inch display with 5000mAh battery.",
    "price": 15999,
    "currency": "INR",
    "category": "Mobiles",
    "stock": 25,
    "rating": 4.6,
    "image": "https://example.com/images/smartphone.jpg",
    "brand": "TechOne",
    "createdAt": "2026-02-06T14:20:00Z"
  },
  {
    "id": 7,
    "name": "Wireless Mouse",
    "description": "Ergonomic mouse with adjustable DPI.",
    "price": 799,
    "currency": "INR",
    "category": "Electronics",
    "stock": 150,
    "rating": 4.0,
    "image": "https://example.com/images/mouse.jpg",
    "brand": "ClickPro",
    "createdAt": "2026-02-07T16:10:00Z"
  },
  {
    "id": 8,
    "name": "Office Chair",
    "description": "Adjustable ergonomic office chair with lumbar support.",
    "price": 8999,
    "currency": "INR",
    "category": "Furniture",
    "stock": 12,
    "rating": 4.4,
    "image": "https://example.com/images/chair.jpg",
    "brand": "ComfortSeat",
    "createdAt": "2026-02-08T10:50:00Z"
  }
]
